### ISSUE TITLE
make js files for every example

### ISSUE THREAD

**Issue by httpete-ire** [kensterz/interview-questions-in-javascript#16]
It might be easier for people to understand the implementation of the examples if they can run the code and play around with it. It would also be nice to have tests for each example. 

I can help out with this if you think it might be helpful 😺

**Comment by kensterz** [comment]
This is actually a very good suggestion. I'll get the first set of files and structures released soon :D Thanks for your suggestion!

**Comment by limichange** [comment]
We can use `jsfiddle.net` or `codepen` :D

**Comment by kennymkchan** [comment]
Great suggestions! Going to use codepen for the simplicity, and already started

**Comment by kennymkchan** [comment]
Created codepens. Closing this issue!
