### ISSUE TITLE
Answer to question 1.4 doesn't handle a case of repeating number in array that is not currentMin

### ISSUE THREAD

**Issue by misstonbon** [kensterz/interview-questions-in-javascript#32]
`array = [7,4,2,9,9,15,1]`
The answer doesn't handle `if array[i] === array[i-1]`
or in the case of array above, `9,9`

**Comment by kennymkchan** [comment]
Hey @misstonbon! Can you give me an example where the code breaks? The code should work provided your array with: `array = [7,4,2,9,9,15,1]`. The answer returned should be `13`, which is the difference between 2 and 15

**Comment by misstonbon** [comment]
https://codepen.io/tanjastroble/pen/ZjaaoZ
